### ISSUE TITLE
Issue occurs when it comes to profiling macros

### ISSUE THREAD

**Issue by Ionizing** [frederic-santos/ob-julia#7]
Hello,

I must say thank you for the excellent work. `ob-ess-julia` can achieve much more than the old `ob-julia` and I also watched this repo.

# issue
I am working on a blog which contains some performance test. This involves some profiling macros (e.g. `@time`), and the issue is here. If I profile some function that returns HUGE objects (e.g. some large `Array`) , the evaluation will produce the returned object only:

```orgmode
#+begin_src ess-julia
@time rand(3,3);
#+end_src

#+RESULTS:
| 0.14787244598120042 | 0.29221271322136544 |   0.5061896798995378 |
| 0.12440932002729221 | 0.15924512639882105 | 0.045874609255543985 |
|  0.9869769299354607 |  0.8996838920278267 |   0.9816670234284175 |

#+begin_src ess-julia
@time rand(3,3)
#+end_src

#+RESULTS:
| 0.6325161384364639 | 0.9381154456632967 |  0.7099371483062931 |
| 0.1999337489636941 | 0.9593296933617066 |  0.7539116922745757 |
| 0.9779359150609555 | 0.8260885438727803 | 0.42433850994855393 |
```

while in an REPL:

```
julia> @time rand(3,3);
  0.000273 seconds (20 allocations: 20.344 KiB)

julia> @time rand(3,3)          # NO SEMICOLON HERE
  0.000005 seconds (1 allocation: 160 bytes)
3×3 Array{Float64,2}:
 0.254155  0.797701  0.307782
 0.23578   0.271436  0.0668501
 0.949984  0.524387  0.303595
```

Well, there does be a way to produce the profile result:

```orgmode
#+begin_src ess-julia :results output
@time rand(3,3);
#+end_src

#+RESULTS:
:   0.000152 seconds (20 allocations: 20.344 KiB)
: 3×3 Array{Float64,2}:
:  0.0401991  0.453899  0.47403
:  0.454261   0.413138  0.520632
:  0.325753   0.667501  0.339036
```

But the returned object is still there.

# Another test
```orgmode
#+begin_src ess-julia :results output
y(x) = x + 1
@time rand(3,3);
#+end_src

#+RESULTS:
: y (generic function with 1 method)
:   0.000180 seconds (20 allocations: 20.344 KiB)
: 3×3 Array{Float64,2}:
:  0.747911  0.743827  0.930585
:  0.964818  0.684683  0.267406
:  0.181975  0.706911  0.099105
```

Well the expected result should not contain `y (generic function with 1 method)`, in my opinion.

Now what I want is to store the profile result and truncate the returned object. I wonder if there are any solutions?

**Comment by Ionizing** [comment]
Oh, I am sorry that I forgot to post my environment:
```
macOS 10.15.1
GNU Emacs 27.1
DoomEmacs v2.0.9 with julia support enabled
ob-ess-julia.el v1.0.3
```

If more info is required, I will post as much as possible.

Looking forward to your reply ^_^

**Comment by frederic-santos** [comment]
Hi @Ionizing , thanks for your report!

Some little comments:

1. I think that your first code block (which assumes `:results value`) behaves roughly as expected: since `@time` does not return a proper value, you can't retrieve it this way. I think `:results output` is the way to go if you use `@time`.
2. Actually, your issue is *almost* solved by switching to a session eval. For instance (do you confirm it's okay for you?):
   ```
   #+begin_src ess-julia :results output :session *julia*
   @time rand(3,3);
   #+end_src
   
   #+RESULTS:
   :   0.000004 seconds (1 allocation: 160 bytes)
   ```
   But there _is_ a problem with the external evaluation here, you're right!
3. "_Well the expected result should not contain y (generic function with 1 method), in my opinion._": I don't know (really!)... this is disputable. I think that most of the `ob-*` backends display the results of _all_ instructions evaluated in the code block when you choose `:results output` (but when you choose `:results value`, only the result of the last one is displayed). I'm not perfectly sure, but I would also say it is the intended behaviour here. I just hope I'm right. :)
4. This last comment is absolutely not related to `ob-ess-julia`, but what about the `@elapsed` macro? For instance:
   ```
   #+begin_src ess-julia :results output :session *julia*
   mytime = @elapsed rand(10,10);
   print(mytime)
   #+end_src
   
   #+RESULTS:
   : 3.472e-6
   ```
   and then you would be able to use and reformat the output stored in the `mytime` variable (which is not possible with `@time`, I think).

**Comment by Ionizing** [comment]
Hi, thank you for your reply!

I've tested the methods you listed above, which generally resolves my problem! Thank you again.

> I think `:results output` is the way to go if you use `@time`.

You're right! `@time` will return the value of expressions, so `:results value` will capture the returned value only. And `:results output` will capture all output. Since I want the profiling result, which comes from `stdout`, I must choose `:results output` if I insist on `@time` macro.

> your issue is *almost* solved by switching to a session eval

Correct! I've tested and I think it is the solution to my problem!

> most of the ob-* backends display the results of all instructions evaluated in the code block 

I just wonder if the block's result should be consistent with REPL, and if not, it is somewhat confusing for users, I guess. I just think that maybe some footnotes on `:session *julia*` or `:results output` should be added to the document to address the differences.

In fact, I searched the documents of `orgmode` and `ob-julia` for the reason why the REPL's results aren't consistent with `org-babel`'s, but ended in vain. So I just suggest adding some explaination in `ob-ess-julia`'s document.

> what about the `@elapsed` macro?

Well, coders do not only pay attention to the time elapsed but also consider the memory utilization. `@elapsed` only shows the time usage. Maybe `@timed` macro is more suitable if someone wants customed print format of profile results, but I am just too lazy to choose it 🤣🤣🤣

Anyway, thanks for your patient reply and I will go on watching this repo 😘

**Comment by frederic-santos** [comment]
Many thanks!

> I just think that maybe some footnotes on :session *julia* or :results output should be added to the document to address the differences.

Totally agreed!

> I will go on watching this repo

An "official" `ob-julia` will be released soon, mainly based on [this repo](https://git.nixo.xyz/nixo/ob-julia). You may also want to take a look at this one. :)

See you!
